# Generated by Django 3.1.4 on 2021-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/profilepic.jpg', upload_to='profile_pictures'),
        ),
    ]
