# Generated by Django 3.1.4 on 2021-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0002_remove_post_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='adminSide.Tag'),
        ),
    ]
